name: CI

permissions: read-all

on:
  push:
    paths:
      - cmd/**
      - pkg/**
      - internal/**
      - .github/workflows/ci.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest
      - name: Check Code Formatting
        run: |
          unformatted_files=$(gofumpt -l .)
          if [ -n "$unformatted_files" ]; then
            echo "Files not formatted:"
            echo "$unformatted_files"
            exit 1
          fi

  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          working-directory: ./
          args: --timeout=5m

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Install CFSSL and CFSSLJSON
        run: |
          go install github.com/cloudflare/cfssl/cmd/cfssl@v1.4.1
          go install github.com/cloudflare/cfssl/cmd/cfssljson@v1.4.1
          cfssl version
          cfssljson --version
      - name: Add CFSSL and CFSSLJSON to PATH
        run: echo "$GOPATH/bin" >> $GITHUB_PATH
      - name: Test
        run: make init gencert test
